# Tags: 3.1-nanoserver-20H2
FROM dotnet/nightly/aspnet:3.1-nanoserver-20H2
FROM dotnet/nightly/aspnet:3.1-nanoserver-2009
FROM dotnet/nightly/aspnet:3.1.21-nanoserver-20H2
FROM dotnet/nightly/aspnet:3.1.21-nanoserver-2009
