# Tags: 5.0-bullseye-slim-arm64v8, 5.0.12-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:5.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:5.0.12-bullseye-slim-arm64v8
