# Tags: 5.0-nanoserver-2009
FROM dotnet/nightly/aspnet:5.0-nanoserver-2009
FROM dotnet/nightly/aspnet:5.0-nanoserver-20H2
FROM dotnet/nightly/aspnet:5.0.12-nanoserver-2009
FROM dotnet/nightly/aspnet:5.0.12-nanoserver-20H2
