# Tags: 6.0-bullseye-slim-arm64v8, 6.0.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0.0-bullseye-slim-arm64v8
