# Tags: 6.0-windowsservercore-ltsc2022, 6.0.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0.0-windowsservercore-ltsc2022
