# Tags: 7.0.0-alpha.1-windowsservercore-ltsc2022, 7.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:7.0.0-alpha.1-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:7.0-windowsservercore-ltsc2022
