# Tags: 3.1-nanoserver-ltsc2022, 3.1.21-nanoserver-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:3.1-nanoserver-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/aspnet:3.1.21-nanoserver-ltsc2022
