# Tags: 3.1-buster-slim-arm64v8, 3.1.21-buster-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:3.1-buster-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:3.1.21-buster-slim-arm64v8
