# Tags: 6.0-alpine-arm64v8, 6.0-alpine3.15-arm64v8, 6.0.0-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0-alpine-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0.0-alpine3.15-arm64v8
