# Tags: 5.0-windowsservercore-ltsc2019, 5.0.12-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/aspnet:5.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/aspnet:5.0.12-windowsservercore-ltsc2019
