# Tags: 7.0-windowsservercore-ltsc2019, 7.0.0-alpha.1-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/aspnet:7.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/aspnet:7.0.0-alpha.1-windowsservercore-ltsc2019
